export const SECOND = 1000;
export const MINUTE = SECOND * 60;
export const HOUR = MINUTE * 60;
export const DAY = HOUR * 24;

export const LOAD_SUCCESS_INTERVAL = HOUR;
export const LOAD_FAILURE_INTERVAL = SECOND * 5;

export const LOAD_HOME_SUCCESS_INTERVAL = LOAD_SUCCESS_INTERVAL;
export const LOAD_HOME_FAILURE_INTERVAL = LOAD_FAILURE_INTERVAL;

export const LOAD_NOTIFICATIONS_SUCCESS_INTERVAL = MINUTE * 10;
export const LOAD_NOTIFICATIONS_FAILURE_INTERVAL = SECOND * 5;

export const LOAD_DOT_CATEGORIES_SUCCESS_INTERVAL = MINUTE * 10;
export const LOAD_DOT_CATEGORIES_FAILURE_INTERVAL = SECOND * 5;
